export const GET_USER_BY_EMAIL = 'GET_USER_BY_EMAIL';
export const USER_LOGIN_HAS_ERROR = 'USER_LOGIN_HAS_ERROR';
export const USER_LOGIN_ERROR_MESSAGE = 'USER_LOGIN_ERROR_MESSAGE';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_HAS_ERROR = 'ADD_USER_HAS_ERROR';
export const ADD_USER_ERROR_MESSAGE = 'ADD_USER_ERROR_MESSAGE';
