export const GET_ITEMS = 'GET_ITEMS';
export const GET_USER_BY_EMAIL = 'GET_USER_BY_EMAIL';
export const USER_LOGIN_HAS_ERROR = 'USER_LOGIN_HAS_ERROR';
export const USER_LOGIN_ERROR_MESSAGE = 'USER_LOGIN_ERROR_MESSAGE';
export const ADD_ITEM = 'ADD_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
